# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2f6a200ac56cb2510de832febf839deac369bf9137e7570efd3171ecd31313fb6107b8a078cac35f9869d3e416b96aa48337d5469dc98ccec876d0be37ca5d3

test:
  secret_key_base: ee3364055a336239229f1c51952f279a2bfdbd8301f30998bc4f41b5503762af62a9144662b5675eb070664b6749eb83ab31248108f0783cd8bca0c0cf9eacc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
